{
 "title": "KaliKillers",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "highest_diff",
    "query": "SELECT MAX(diff) from message_counts"
   }
  ]
 },
 "panels": [
  {
   "title": "Message Counter",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "#Messages Total" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  count\nFROM message_counts\nWHERE\n  $__timeFilter(created_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Current Messages",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  count\nFROM message_counts\nWHERE\n  $__timeFilter(created_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Average diff",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  diff\nFROM message_counts\nWHERE\n  $__timeFilter(created_at) AND\n  diff >= 0\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Message Diff",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "# Messages" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  diff AS \"diff\"\nFROM message_counts\nWHERE\n  $__timeFilter(created_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Last diff",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  diff\nFROM message_counts\nWHERE\n  $__timeFilter(created_at) AND\n  diff >= 0\nORDER BY 1"
    }
   ]
  }
 ]
}