{
 "title": "KaliKillers",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "highest_diff",
    "query": "SELECT MAX(diff) from message_counts"
   },
   { "name": "kali_id", "query": "-1001090867629" },
   { "name": "dieter_id", "query": "218403767" },
   { "name": "gerben_id", "query": "189674713" },
   { "name": "bart_id", "query": "135502440" },
   { "name": "kenny_id", "query": "172179034" },
   { "name": "tillo_id", "query": "145717123" },
   { "name": "hannes_id", "query": "213583950" },
   { "name": "octaaf_id", "query": "502563984" }
  ]
 },
 "panels": [
  {
   "title": "Message Counter",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "#Messages Total" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  count\nFROM message_counts\nWHERE\n  $__timeFilter(created_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Current Messages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  count\nFROM message_counts\nWHERE\n  $__timeFilter(created_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Diff during timerange",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  diff\nFROM message_counts\nWHERE\n  $__timeFilter(created_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Last diff",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  diff\nFROM message_counts\nWHERE\n  $__timeFilter(created_at) AND\n  diff >= 0\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Average diff",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  diff\nFROM message_counts\nWHERE\n  $__timeFilter(created_at) AND\n  diff >= 0\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Message Diff",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "# Messages" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  diff AS \"diff\"\nFROM message_counts\nWHERE\n  $__timeFilter(created_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Lowest Diff",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  diff\nFROM message_counts\nWHERE\n  $__timeFilter(created_at) AND\n  diff >= 0\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Highest Diff",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  diff\nFROM message_counts\nWHERE\n  $__timeFilter(created_at) AND\n  diff >= 0\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Quotes per user",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1h),\n  count(user_id) AS \"Dieter\"\nFROM quotes\nWHERE\n  $__timeFilter(created_at) AND\n  chat_id = $kali_id AND\n  user_id = $dieter_id\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1h),\n  count(user_id) AS \"Gerben\"\nFROM quotes\nWHERE\n  $__timeFilter(created_at) AND\n  chat_id = $kali_id AND\n  user_id = $gerben_id\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1h),\n  count(user_id) AS \"Bart\"\nFROM quotes\nWHERE\n  $__timeFilter(created_at) AND\n  chat_id = $kali_id AND\n  user_id = $bart_id\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1h),\n  count(user_id) AS \"Kenny\"\nFROM quotes\nWHERE\n  $__timeFilter(created_at) AND\n  chat_id = $kali_id AND\n  user_id = $kenny_id\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1h),\n  count(user_id) AS \"Tillo\"\nFROM quotes\nWHERE\n  $__timeFilter(created_at) AND\n  chat_id = $kali_id AND\n  user_id = $tillo_id\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1h),\n  count(user_id) AS \"Hannes\"\nFROM quotes\nWHERE\n  $__timeFilter(created_at) AND\n  chat_id = $kali_id AND\n  user_id = $hannes_id\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1h),\n  count(user_id) AS \"Octaaf\"\nFROM quotes\nWHERE\n  $__timeFilter(created_at) AND\n  chat_id = $kali_id AND\n  user_id = $octaaf_id\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Check-ins per user",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 16 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1h),\n  count(user_id) AS \"Dieter\"\nFROM kalicheckers\nWHERE\n  $__timeFilter(created_at) AND\n  user_id = $dieter_id\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1h),\n  count(user_id) AS \"Gerben\"\nFROM kalicheckers\nWHERE\n  $__timeFilter(created_at) AND\n  user_id = $gerben_id\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1h),\n  count(user_id) AS \"Bart\"\nFROM kalicheckers\nWHERE\n  $__timeFilter(created_at) AND\n  user_id = $bart_id\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1h),\n  count(user_id) AS \"Kenny\"\nFROM kalicheckers\nWHERE\n  $__timeFilter(created_at) AND\n  user_id = $kenny_id\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1h),\n  count(user_id) AS \"Tillo\"\nFROM kalicheckers\nWHERE\n  $__timeFilter(created_at) AND\n  user_id = $tillo_id\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1h),\n  count(user_id) AS \"Hannes\"\nFROM kalicheckers\nWHERE\n  $__timeFilter(created_at) AND\n  user_id = $hannes_id\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "#Quotes",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 16 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1h),\n  type AS metric,\n  count(chat_id) AS \"chat_id\"\nFROM msgquotes\nWHERE\n  $__timeFilter(created_at) AND\n  chat_id = $kali_id\nGROUP BY 1,2\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1h),\n  count(chat_id) AS \"text_quote\"\nFROM quotes\nWHERE\n  $__timeFilter(created_at) AND\n  chat_id = $kali_id\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}