{
 "title": "KaliWorldWide",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   { "name": "kali_id", "query": "-1001090867629" }
  ]
 },
 "panels": [
  {
   "title": "Where history",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 22, "w": 14, "x": 0, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  ' ' AS metric,\n  lat,\n  lng,\n  name\nFROM location_histories\nWHERE\n  $__timeFilter(created_at) AND\n  chat_id = $kali_id\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Locations",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 14, "w": 8, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1h),\n  name AS metric,\n  count(message_id) AS \"message_id\"\nFROM location_histories\nWHERE\n  $__timeFilter(created_at) AND\n  chat_id = $kali_id\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Location Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 14, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  count(message_id) AS \"Queries\"\nFROM location_histories\nWHERE\n  $__timeFilter(created_at) AND\n  chat_id = $kali_id\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}