# This file shoudln't be touched
# Database config is in settings.toml
# This is legacy because of gobuffalo/pop's hard requirement on this file

development:
  url: {{envOr "DATABASE_URL" "postgres://username:password@127.0.0.1:5432/octaaf_db_name?sslmode=disable" }}

test:
  url: {{envOr "DATABASE_URL" "postgres://username:password@127.0.0.1:5432/octaaf_db_name?sslmode=disable" }}

production:
  url: {{envOr "DATABASE_URL" "postgres://username:password@127.0.0.1:5432/octaaf_db_name?sslmode=disable" }}
