# This file shoudln't be touched
# Database config is in settings.toml
# This is legacy because of gobuffalo/pop's hard requirement on this file

development:
  url: {{ env "DATABASE_URI" }}

test:
  url: {{ env "DATABASE_URI" }}

production:
  url: {{ env "DATABASE_URI" }}
